language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow

matrix:
  include:
    - python: 2.7
      env:
        VERSION="9.0" TESTS="1" LINT_CHECK="0"
        INSTANCE_ALIVE="1" INCLUDE="broken_module" SERVER_EXPECTED_ERRORS="2"  # test errors are detected
    - python: 2.7
      env:
        VERSION="9.0" TESTS="1" LINT_CHECK="0"
        EXCLUDE="broken_module,broken_lint,broken_no_access_rule" OPTIONS="--log-level=debug" INSTALL_OPTIONS="--log-level=info" RUN_COMMAND_MQT_CREATE_FOLDER='mkdir /tmp/tests'
    - python: 2.7
      env:
        VERSION="9.0" TESTS="1" LINT_CHECK="0"
        INCLUDE="test_module,second_module" UNIT_TEST="1"
    - python: 2.7
      env:
        VERSION="9.0" TESTS="1" LINT_CHECK="0"
        INCLUDE="test_module,second_module" ODOO_REPO="OCA/OCB" MQT_TEMPLATE_DB='mqt_odoo_template_core' MQT_TEST_DB='mqt_odoo_core'
    - python: 2.7
      env:
        VERSION="" TESTS="0" LINT_CHECK="1"
        PYLINT_EXPECTED_ERRORS="35"
    - python: 3.5
      env:
        VERSION="" TESTS="0" LINT_CHECK="1"
        PYLINT_EXPECTED_ERRORS="36"
    - python: 3.7-dev
      env:
        VERSION="" TESTS="0" LINT_CHECK="1"
        PYLINT_EXPECTED_ERRORS="36"
    - python: 3.5
      env:
        VERSION="11.0" ODOO_REPO="OCA/OCB" TESTS="1" LINT_CHECK="0"
        INCLUDE="test_module,second_module"
    - python: 3.7-dev
      env:
        VERSION="11.0" ODOO_REPO="OCA/OCB" TESTS="1" LINT_CHECK="0"
        INCLUDE="test_module,second_module"
    - python: 3.5
      env:
        VERSION="12.0" ODOO_REPO="OCA/OCB" TESTS="1" LINT_CHECK="0"
        INCLUDE="test_module,second_module"
    - python: 3.7-dev
      env:
        VERSION="12.0" ODOO_REPO="OCA/OCB" TESTS="1" LINT_CHECK="0"
        INCLUDE="test_module,second_module"

